[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Build context for production
[context.production]
  command = "npm run build"

# Build context for deploy previews
[context.deploy-preview]
  command = "npm run build"

# Build context for branch deploys
[context.branch-deploy]
  command = "npm run build"